[build]
  base    = "docs/"
  publish = "docs/public/"
  command = "./generate-docs.sh"
[build.environment]
  NPM_VERSION = "6"
[dev]
  command = "npm run build"
[context.dev.environment]
  SKIP_INDEXING = "false"

